server:
  port: 8092
  
spring:
  application:
    name: EmployeeService
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka
    register-with-eureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.charan.*: DEBUG
