server:
  port: 8092
  
spring:
  application:
    name: EmployeeService
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka
      healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 60
